"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xqbb%%0v0*0*dn408q^f)#u7sgib^p(fcl@wf(kv^2zpnti49d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # DRF 추가
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist', 
    
    # 앱 추가
    'bookmarks',    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# DRF 전역 설정
# ===== REST Framework 설정 =====
REST_FRAMEWORK = {
    # 기본 인증 방식 설정
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # JWT 인증을 기본으로 사용
        'rest_framework_simplejwt.authentication.JWTAuthentication',

        # 개발 편의를 위해 Session 인증도 유지 (Browsable API용)
        # 프로덕션에서는 제거 권장
        'rest_framework.authentication.SessionAuthentication',
    ],

    # 기본 권한 정책
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     'rest_framework.permissions.IsAuthenticated',
    # ],
    # → 일단 주석 처리 (View마다 개별 설정할 예정)
}

# ===== JWT 설정 =====
from datetime import timedelta

SIMPLE_JWT = {
    # Access Token 수명
    # 짧게 설정하여 보안 강화 (탈취되어도 금방 만료)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    # 실무 권장: 15분~1시간
    # MVP 단계: 1시간 (개발 편의)

    # Refresh Token 수명
    # 길게 설정하여 사용자 편의 향상
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 실무 권장: 7일~30일

    # Token 자동 갱신 여부
    # True: Refresh 시 Refresh Token도 새로 발급
    # False: Refresh Token은 그대로 유지
    'ROTATE_REFRESH_TOKENS': True,
    # 권장: True (보안 강화)

    # 이전 Refresh Token 무효화 여부
    # ROTATE_REFRESH_TOKENS=True일 때만 의미 있음
    'BLACKLIST_AFTER_ROTATION': True,
    # 권장: True (이전 토큰 재사용 방지)

    # 서명 알고리즘
    'ALGORITHM': 'HS256',
    # HS256: 대칭키 암호화 (서버만 복호화 가능)
    # RS256: 비대칭키 (공개키로 검증 가능) - MSA 환경에 유리

    # 서명 키 (Django SECRET_KEY 사용)
    'SIGNING_KEY': SECRET_KEY,
    # 프로덕션: 별도의 JWT_SECRET_KEY 사용 권장

    # Payload에 포함할 사용자 식별 필드
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token 헤더 이름
    'AUTH_HEADER_TYPES': ('Bearer',),
    # 요청 시: Authorization: Bearer <token>

    # Token 헤더 이름
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
